FIRST_NAME_INPUTFIELD = '//label[contains(text(),"First Name")]/../input'
LAST_NAME_INPUTFIELD = '//label[contains(text(),"Last Name")]/../input'
COMPANY_INPUTFIELD = '//label[contains(text(),"Company Name")]/../input'
ROLE_INPUTFIELD = '//label[contains(text(),"Role in Company")]/../input'
ADRESS_INPUTFIELD = '//label[contains(text(),"Address")]/../input'
EMAIL_INPUTFIELD = '//label[contains(text(),"Email")]/../input'
PHONE_INPUTFIELD = '//label[contains(text(),"Phone Number")]/../input'
SUBMIT_BUTTON = '//input[@class="btn uiColorButton"]'
